package org.outofoffice.lib.core.ui;

import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

@Target(FIELD)
@Retention(RUNTIME) // todo bytecode generation
public @interface Id {
    boolean autoGenerated() default false;
}
